
## 이미지 변경시 재시작!
# kubectl rollout restart deployment catalog-service


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: ytkwon91/catalog-service:0.1
          imagePullPolicy: Always             # 항상 새 이미지 Pull
          ports:
            - containerPort: 30093
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: NodePort
  selector:
    app: catalog-service
  ports:
    - port: 30093
      targetPort: 30093
      nodePort: 30093   # 외부에서 접근 시 NodePort
