apiVersion: v1
kind: Pod
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  containers:
    - name: config-service
      image: ytkwon91/config-service:0.1
      ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088   # 브라우저 접속 시 포트 (30000~32767 범위 내 자유롭게 선택)

