apiVersion: v1
kind: Pod
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  containers:
    - name: discovery-service
      image: ytkwon91/discovery-service:0.1
      ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: NodePort
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30061   # 브라우저 접속 시 포트 (30000~32767 범위 내 자유롭게 선택)

