apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb-container
      image: mariadb:10.5
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: "1234"  # 👉 진짜 사용 시 Secret으로 분리하는 게 좋음
      ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
