
## 이미지 변경시 재시작!
# kubectl rollout restart deployment user-service


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ytkwon91/user-service:0.1   # 버전 변경 시 여기를 수정
          imagePullPolicy: Always            # 항상 새 이미지 Pull
          ports:
            - containerPort: 30091
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 30091
      targetPort: 30091
      nodePort: 30091
