---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: 2   # 안정성을 위해 최소 2개
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
          resources:
            requests:
              cpu: "200m"      # 최소 CPU 보장
              memory: "512Mi"  # 최소 메모리 보장
            limits:
              cpu: "500m"      # 최대 CPU 제한
              memory: "1Gi"    # 최대 메모리 제한
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - name: http
      port: 9411
      targetPort: 9411
  type: ClusterIP  # 내부 통신용 (Spring 서비스 → Zipkin)
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-nodeport
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - name: http
      port: 9411
      targetPort: 9411
      nodePort: 30941
  type: NodePort  # 외부 접속용 (브라우저로 Zipkin UI 확인)
