server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///C:/dev/git-local-repo
        git:
          uri: file:///C:/dev/git-local-repo
          default-label: master
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#token:
#  secret: jwt_token_should_be_more_than_32
management:
  endpoints:
    web:
      exposure:
        include: busenv, busrefresh

